apiVersion: v1
kind: Service
metadata:
  # Watchout with this service name:
  # https://medium.com/@varunreddydaaram/kubernetes-did-not-work-with-apache-spark-de923ae7ab5c
  # This cannot be called 'spark-master'
  name: spark-k8
  labels:
    component: "spark-master"
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: "spark-master"
  type: LoadBalancer