apiVersion: v1
kind: Service
metadata:
  name: spark-webui
  labels:
    component: "spark-master"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: "spark-master"
  type: LoadBalancer